### ISSUE TITLE
Error on configure script

### ISSUE THREAD

**Issue by Rvanlaak** [loggly/install-script#73]
The script shows an error when I try to execute any command:

```
root@web:~# python configure-syslog.py loggly_help

*************************************************************
****** Starting Loggly Syslog Configuration Script ******
*************************************************************

Traceback (most recent call last):
  File "configure-syslog.py", line 1479, in main
    log({"status":"start", "args": vars(options)})
  File "configure-syslog.py", line 1209, in log
    log_msg(json.dumps(msg_dict))
  File "configure-syslog.py", line 1237, in log_msg
    (LOGGLY_SYSLOG_SERVER, LOGGLY_SYSLOG_PORT))
error: [Errno 1] Operation not permitted

Configure script has errors
```

**Comment by mostlyjason** [comment]
I think this is the older script. Have you tried using the newer configure-linux.sh instead?

**Comment by Rvanlaak** [comment]
The newer script solved it :+1:  Don't know how it was even possible that we found the old script.
